-- Spoke Tables (A-E) for Preciso

create table if not exists public.spoke_a_strategy (
  id uuid default gen_random_uuid() primary key,
  entity text,
  period text,
  instruction text,
  input_context text,
  output_strategy text,
  analysis_trace text,
  confidence text,
  created_at timestamptz default now()
);

create table if not exists public.spoke_b_quant_meta (
  id uuid default gen_random_uuid() primary key,
  dataset_name text,
  partition_year text,
  partition_month text,
  record_count integer,
  storage_path text,
  created_at timestamptz default now()
);

create table if not exists public.spoke_c_rag_context (
  id uuid default gen_random_uuid() primary key,
  chunk_id text unique,
  entity text,
  period text,
  source text,
  text_content text,
  keywords text[],
  created_at timestamptz default now()
);

create table if not exists public.spoke_d_graph (
  id uuid default gen_random_uuid() primary key,
  head_node text not null,
  relation text not null,
  tail_node text not null,
  properties jsonb,
  created_at timestamptz default now()
);

create table if not exists public.ai_training_sets (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  metadata jsonb,
  input_features jsonb,
  reasoning_chain jsonb,
  output_narrative text,
  training_prompt text
);
