-- Spoke Tables (A-E) for Preciso

create table if not exists public.spoke_a_strategy (
  id uuid default gen_random_uuid() primary key,
  entity text,
  period text,
  instruction text,
  input_context text,
  output_strategy text,
  analysis_trace text,
  confidence text,
  created_at timestamptz default now()
);

create table if not exists public.spoke_b_quant_meta (
  id uuid default gen_random_uuid() primary key,
  dataset_name text,
  partition_year text,
  partition_month text,
  record_count integer,
  storage_path text,
  created_at timestamptz default now()
);

create table if not exists public.spoke_c_rag_context (
  id uuid default gen_random_uuid() primary key,
  chunk_id text unique,
  entity text,
  period text,
  source text,
  text_content text,
  keywords text[],
  created_at timestamptz default now()
);

create table if not exists public.spoke_d_graph (
  id uuid default gen_random_uuid() primary key,
  case_id text,
  doc_id text,
  head_node text not null,
  relation text not null,
  tail_node text not null,
  properties jsonb,
  event_time timestamptz,
  valid_from timestamptz,
  valid_to timestamptz,
  observed_at timestamptz default now(),
  time_source text,
  time_granularity text,
  created_at timestamptz default now()
);

create index if not exists idx_spoke_d_graph_case_id on public.spoke_d_graph(case_id);
create index if not exists idx_spoke_d_graph_event_time on public.spoke_d_graph(event_time);
create index if not exists idx_spoke_d_graph_valid_window on public.spoke_d_graph(valid_from, valid_to);

create table if not exists public.audit_log (
  id uuid default gen_random_uuid() primary key,
  case_id text not null,
  event_type text not null,
  stage text not null,
  status text not null,
  payload jsonb,
  created_at timestamptz default now()
);

create index if not exists idx_audit_log_case_id on public.audit_log(case_id);
create index if not exists idx_audit_log_created_at on public.audit_log(created_at);

create table if not exists public.ai_training_sets (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  metadata jsonb,
  input_features jsonb,
  reasoning_chain jsonb,
  output_narrative text,
  training_prompt text
);
